export { default as EducationSection } from "./EducationSection";
export { default as CoverLettersSection } from "./CoverLettersSection";
export { default as WorkExperienceSection } from "./WorkExperienceSection";
export { default as CertificationsSection } from "./CertificationsSection";
export { default as SkillsSection } from "./SkillsSection";
export { default as InterestsSection } from "./InterestsSection";
export { default as LanguagesSection } from "./LanguagesSection";
export { default as PersonalDetailsSection } from "./PersonalDetailsSection";
export { default as BioSection } from "./BioSection";
